'use client'

import { useActionState } from 'react'

import type { OpportunityAssigneeOption } from '../../../lib/opportunities/detail'
import type { Theme, ThemeFollowup, ThemeResponsibility } from '../../../lib/themes/themes'
import {
  addThemeResponsibilityAction,
  createThemeAction,
  createThemeFollowupAction,
  removeThemeResponsibilityAction,
  transitionThemeAction,
  updateThemeAction,
  type ThemeActionState,
} from './actions'

const initialState: ThemeActionState = { status: 'idle', message: null }
const priorities = { low: 'Baja', normal: 'Normal', high: 'Alta', urgent: 'Urgente' }
const statuses = { active: 'Activo', monitoring: 'En seguimiento', paused: 'Pausado', closed: 'Cerrado' }
const responsibilityRoles = { principal: 'Principal', responsible: 'Responsable', promoter: 'Impulsor' }
const followupTypes = { general: 'Novedad general', meeting: 'Reunión', decision: 'Decisión', commitment: 'Compromiso', next_step: 'Próximo paso', result: 'Resultado', observation: 'Observación' }

function Feedback({ state }: { state: ThemeActionState }) {
  return state.message ? <p className={`mt-3 text-sm ${state.status === 'error' ? 'text-red-700' : 'text-emerald-700'}`}>{state.message}</p> : null
}

const inputClass = 'mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm'

export function ThemeCreateForm({ users }: { users: OpportunityAssigneeOption[] }) {
  const [state, action, pending] = useActionState(createThemeAction, initialState)
  return <form action={action} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Nombre<input name="name" required minLength={3} maxLength={200} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Descripción<textarea name="description" required minLength={10} maxLength={10000} rows={4} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Propósito<textarea name="purpose" required minLength={3} maxLength={10000} rows={3} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700">Prioridad<select name="priority" defaultValue="normal" className={inputClass}>{Object.entries(priorities).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Fecha de inicio<input name="start_date" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Situación actual<textarea name="current_summary" minLength={3} maxLength={10000} rows={3} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Alcance territorial<textarea name="territorial_scope_summary" minLength={3} maxLength={2000} rows={2} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700">Principal inicial<select name="principal_internal_user_id" className={inputClass}><option value="">Sin asignar</option>{users.map((user) => <option key={user.id} value={user.id}>{user.display_name}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Fundamento inicial<textarea name="rationale" required minLength={3} maxLength={10000} rows={2} className={inputClass} /></label></div>
    <Feedback state={state} /><button disabled={pending} className="mt-5 rounded-xl bg-[#1E3A5F] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{pending ? 'Creando...' : 'Crear tema'}</button>
  </form>
}

export function ThemeGovernanceForms({ theme, canManage, canGovern }: { theme: Theme; canManage: boolean; canGovern: boolean }) {
  const [updateState, updateAction, updatePending] = useActionState(updateThemeAction.bind(null, theme.theme_id), initialState)
  const [transitionState, transitionAction, transitionPending] = useActionState(transitionThemeAction.bind(null, theme.theme_id), initialState)
  return <div className="space-y-5">
    {canManage ? <details className="rounded-2xl border border-slate-200 bg-white shadow-sm"><summary className="cursor-pointer px-5 py-4 text-sm font-semibold text-[#1E3A5F]">Editar datos del tema</summary><form action={updateAction} className="grid gap-4 border-t border-slate-200 p-5 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Nombre<input name="name" required minLength={3} maxLength={200} defaultValue={theme.name} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Descripción<textarea name="description" required minLength={10} maxLength={10000} defaultValue={theme.description} rows={3} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Propósito<textarea name="purpose" required minLength={3} maxLength={10000} defaultValue={theme.purpose} rows={3} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700">Prioridad<select name="priority" defaultValue={theme.priority} className={inputClass}>{Object.entries(priorities).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Inicio<input name="start_date" type="date" required defaultValue={theme.start_date} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Situación actual<textarea name="current_summary" minLength={3} maxLength={10000} defaultValue={theme.current_summary ?? ''} rows={3} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Alcance territorial<textarea name="territorial_scope_summary" minLength={3} maxLength={2000} defaultValue={theme.territorial_scope_summary ?? ''} rows={2} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Fundamento del cambio<textarea name="rationale" required minLength={3} maxLength={10000} rows={2} className={inputClass} /></label><div className="sm:col-span-2"><Feedback state={updateState} /><button disabled={updatePending} className="mt-3 rounded-xl bg-[#1E3A5F] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{updatePending ? 'Guardando...' : 'Guardar cambios'}</button></div></form></details> : null}
    {canGovern ? <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-950">Estado</h2><form action={transitionAction} className="mt-4"><select name="status" defaultValue={theme.status} className="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm">{Object.entries(statuses).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><textarea name="rationale" required minLength={3} maxLength={10000} rows={2} placeholder="Motivo del cambio..." className={`${inputClass} mt-3`} /><textarea name="closing_summary" minLength={3} maxLength={10000} rows={2} placeholder="Síntesis final (obligatoria al cerrar)..." className={`${inputClass} mt-3`} /><Feedback state={transitionState} /><button disabled={transitionPending} className="mt-3 rounded-xl border border-[#2F5D8C] px-4 py-2.5 text-sm font-semibold text-[#1E3A5F] disabled:opacity-50">{transitionPending ? 'Actualizando...' : 'Actualizar estado'}</button></form></section> : null}
  </div>
}

export function ThemeResponsibilities({ themeId, responsibilities, users, canGovern }: { themeId: string; responsibilities: ThemeResponsibility[]; users: OpportunityAssigneeOption[]; canGovern: boolean }) {
  const [state, action, pending] = useActionState(addThemeResponsibilityAction.bind(null, themeId), initialState)
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-950">Responsabilidades</h2><div className="mt-4 space-y-3">{responsibilities.filter((item) => !item.ended_at).map((item) => <ThemeResponsibilityCard key={item.responsibility_id} themeId={themeId} responsibility={item} canGovern={canGovern} />)}{!responsibilities.some((item) => !item.ended_at) ? <p className="text-sm text-slate-500">No hay responsabilidades activas.</p> : null}</div>{canGovern ? <form action={action} className="mt-5 grid gap-3 border-t border-slate-200 pt-5 sm:grid-cols-2"><select name="internal_user_id" required className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><option value="">Elegir persona...</option>{users.map((user) => <option key={user.id} value={user.id}>{user.display_name}</option>)}</select><select name="responsibility_role" defaultValue="responsible" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm">{Object.entries(responsibilityRoles).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><textarea name="rationale" required minLength={3} maxLength={10000} rows={2} placeholder="Fundamento de la asignación..." className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm sm:col-span-2" /><div className="sm:col-span-2"><Feedback state={state} /><button disabled={pending} className="mt-3 rounded-xl bg-[#1E3A5F] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{pending ? 'Asignando...' : 'Asignar responsabilidad'}</button></div></form> : null}</section>
}

function ThemeResponsibilityCard({ themeId, responsibility, canGovern }: { themeId: string; responsibility: ThemeResponsibility; canGovern: boolean }) {
  const [state, action, pending] = useActionState(removeThemeResponsibilityAction.bind(null, themeId, responsibility.responsibility_id), initialState)
  return <article className="rounded-xl bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{responsibility.display_name}</strong><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-700">{responsibilityRoles[responsibility.responsibility_role]}</span></div><p className="mt-2 text-sm text-slate-600">{responsibility.rationale}</p>{canGovern ? <form action={action} className="mt-3 flex flex-col gap-2 sm:flex-row"><input name="rationale" required minLength={3} maxLength={10000} placeholder="Motivo de finalización..." className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2 text-sm" /><button disabled={pending} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 disabled:opacity-50">Finalizar</button><Feedback state={state} /></form> : null}</article>
}

export function ThemeFollowups({ themeId, followups, users, canFollowup, isClosed }: { themeId: string; followups: ThemeFollowup[]; users: OpportunityAssigneeOption[]; canFollowup: boolean; isClosed: boolean }) {
  const [state, action, pending] = useActionState(createThemeFollowupAction.bind(null, themeId), initialState)
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-950">Seguimiento</h2>{followups.length ? <ul className="mt-4 space-y-3">{followups.map((item) => <li key={item.followup_id} className="rounded-xl bg-slate-50 p-4 text-sm text-slate-700"><div className="flex flex-wrap justify-between gap-2"><strong>{followupTypes[item.followup_type]}</strong><time className="text-xs text-slate-500">{new Intl.DateTimeFormat('es-AR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(item.occurred_at))}</time></div><p className="mt-2 whitespace-pre-line">{item.detail}</p><p className="mt-2 text-xs text-slate-500">Registró: {item.created_by_display_name}{item.responsible_display_name ? ` · Responsable: ${item.responsible_display_name}` : ''}{item.next_due_at ? ` · Próximo vencimiento: ${new Intl.DateTimeFormat('es-AR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(item.next_due_at))}` : ''}</p></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">Todavía no hay seguimientos.</p>}{canFollowup && !isClosed ? <form action={action} className="mt-5 grid gap-3 border-t border-slate-200 pt-5 sm:grid-cols-2"><select name="followup_type" defaultValue="general" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm">{Object.entries(followupTypes).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select name="responsible_internal_user_id" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><option value="">Sin responsable específico</option>{users.map((user) => <option key={user.id} value={user.id}>{user.display_name}</option>)}</select><textarea name="detail" required minLength={3} maxLength={10000} rows={3} placeholder="Detalle del seguimiento..." className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm sm:col-span-2" /><label className="text-sm text-slate-600">Fecha del hecho<input name="occurred_at" type="datetime-local" className={inputClass} /></label><label className="text-sm text-slate-600">Próximo vencimiento<input name="next_due_at" type="datetime-local" className={inputClass} /></label><div className="sm:col-span-2"><Feedback state={state} /><button disabled={pending} className="mt-3 rounded-xl bg-[#1E3A5F] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{pending ? 'Registrando...' : 'Registrar seguimiento'}</button></div></form> : isClosed ? <p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm text-slate-500">El tema está cerrado. Reactivalo antes de registrar nuevos seguimientos.</p> : null}</section>
}
