'use client'

import Link from 'next/link'
import { useCallback, useState } from 'react'
import { RemoteListPagination } from '../../../components/remote-list-pagination'
import { useRemoteReferenceList, type RemoteReferencePage } from '../../../hooks/use-remote-reference-list'
import type { Communication, CommunicationStatus } from '../../../lib/communications/communications'

const statusLabels: Record<CommunicationStatus, string> = { draft: 'Borrador', audience_resolved: 'Audiencia resuelta', recipients_confirmed: 'Destinatarios confirmados', cancelled: 'Cancelada' }
const typeLabels: Record<Communication['communication_type'], string> = { general: 'General', convocation: 'Convocatoria', reminder: 'Recordatorio', follow_up: 'Seguimiento', request_information: 'Solicitud de información', update: 'Actualización' }
function date(value: string) { return new Intl.DateTimeFormat('es-AR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) }

export function CommunicationsDirectory({ initialItems, initialNextCursor }: { initialItems: Communication[]; initialNextCursor: string | null }) {
  const [status, setStatus] = useState<'' | CommunicationStatus>('')
  const fetchPage = useCallback(async ({ query, cursor, signal }: { query: string; cursor: string | null; signal: AbortSignal }) => {
    const params = new URLSearchParams({ q: query, limit: '50' }); if (cursor) params.set('cursor', cursor); if (status) params.set('status', status)
    const response = await fetch(`/api/panel/comunicaciones?${params}`, { signal, cache: 'no-store' }); if (!response.ok) throw new Error('No se pudo cargar comunicaciones.'); return await response.json() as RemoteReferencePage<Communication>
  }, [status])
  const directory = useRemoteReferenceList({ contextKey: `communications:${status}`, getItemKey: (item: Communication) => item.communication_id, fetchPage, enabledInitially: true })
  const items = directory.query || status ? directory.items : initialItems
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end gap-3"><label className="min-w-56 flex-1"><span className="text-sm font-semibold text-slate-700">Buscar asunto o cuerpo</span><input type="search" value={directory.query} onFocus={directory.open} onChange={(event) => directory.setQuery(event.target.value)} placeholder="Buscar comunicaciones..." className="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm" /></label><label><span className="text-sm font-semibold text-slate-700">Estado</span><select value={status} onChange={(event) => setStatus(event.target.value as '' | CommunicationStatus)} className="mt-2 min-h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="">Todos</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><div className="mt-5 space-y-3" aria-live="polite">{directory.initialLoading && (directory.query || status) ? <p className="text-sm text-slate-500">Cargando comunicaciones...</p> : null}{directory.initialError ? <div role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{directory.initialError} <button type="button" onClick={directory.retry} className="ux-button ml-2 font-semibold underline">Reintentar</button></div> : null}{items.length === 0 && !directory.initialLoading ? <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">No hay comunicaciones que coincidan con los filtros.</p> : items.map((item) => <Link key={item.communication_id} href={`/panel/comunicaciones/${item.communication_id}`} className="block rounded-xl border border-slate-200 bg-slate-50 p-4 transition hover:border-[#2F5D8C]/40 hover:bg-white"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold text-slate-950">{item.subject}</p><p className="mt-1 text-sm text-slate-600">{typeLabels[item.communication_type]} · {item.context_type === 'independent' ? 'Sin contexto' : item.context_title ?? item.context_type}</p></div><span className="rounded-full bg-[#2F5D8C]/10 px-3 py-1 text-xs font-semibold text-[#1E3A5F]">{statusLabels[item.status]}</span></div><p className="mt-3 text-xs text-slate-500">{item.created_by_display_name} · {date(item.updated_at)} · {item.included_recipient_count} incluidos</p></Link>)}</div>{directory.query || status ? <RemoteListPagination key={directory.paginationKey} hasMore={directory.hasMore} loadingMore={directory.loadingMore} error={directory.loadMoreError} onLoadMore={directory.loadMore} /> : initialNextCursor ? <RemoteListPagination hasMore loadingMore={false} onLoadMore={directory.open} autoLoad={false} /> : null}</section>
}
