'use client'

import {
  useActionState,
  useState,
} from 'react'
import type { OpportunityAssigneeOption } from '../../../lib/opportunities/detail'
import type { ProjectDeliverable, ProjectParticipant } from '../../../lib/projects/projects'
import { addProjectParticipantAction, createProjectDeliverableAction, removeProjectParticipantAction, transitionProjectDeliverableAction, type ProjectActionState } from './actions'
import { ProjectParticipantPicker } from './project-participant-picker'

const initialState: ProjectActionState = { status: 'idle', message: null }
const deliverableLabels = { planned: 'Planificado', in_progress: 'En curso', delivered: 'Entregado', accepted: 'Aceptado', cancelled: 'Cancelado' }

function Feedback({ state }: { state: ProjectActionState }) {
  return state.message ? <p className={`mt-3 text-sm ${state.status === 'error' ? 'text-red-700' : 'text-emerald-700'}`}>{state.message}</p> : null
}

function ParticipantItem({ projectId, participant }: { projectId: string; participant: ProjectParticipant }) {
  const [state, action, pending] = useActionState(removeProjectParticipantAction.bind(null, projectId, participant.participant_id), initialState)
  return <li className="rounded-xl bg-slate-50 p-3 text-sm text-slate-700"><strong>{participant.display_name}</strong> · {participant.participation_role}<p className="mt-1">{participant.contribution_summary}</p><details className="mt-2"><summary className="cursor-pointer text-xs font-semibold text-slate-600">Retirar participante</summary><form action={action} className="mt-2 flex flex-wrap gap-2"><input name="rationale" required minLength={3} maxLength={10000} placeholder="Motivo del retiro..." className="min-w-52 flex-1 rounded-lg border border-slate-300 px-3 py-2 text-sm" /><button disabled={pending} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold disabled:opacity-50">{pending ? 'Retirando...' : 'Retirar'}</button></form><Feedback state={state} /></details></li>
}

function DeliverableItem({ projectId, deliverable }: { projectId: string; deliverable: ProjectDeliverable }) {
  const [state, action, pending] = useActionState(transitionProjectDeliverableAction.bind(null, projectId, deliverable.deliverable_id), initialState)
  return <li className="rounded-xl bg-slate-50 p-3 text-sm text-slate-700"><div className="flex flex-wrap justify-between gap-2"><strong>{deliverable.title}</strong><span>{deliverableLabels[deliverable.status]}</span></div><p className="mt-1">{deliverable.description}</p><p className="mt-2 text-xs text-slate-500">Responsable: {deliverable.responsible_display_name ?? 'Sin asignar'}{deliverable.target_date ? ` · Fecha objetivo: ${new Intl.DateTimeFormat('es-AR').format(new Date(`${deliverable.target_date}T12:00:00`))}` : ''}</p>{deliverable.result_summary ? <p className="mt-2 text-xs"><strong>Resultado:</strong> {deliverable.result_summary}<br /><strong>Evidencia:</strong> {deliverable.evidence_reference}</p> : null}<details className="mt-3"><summary className="cursor-pointer text-xs font-semibold text-[#1E3A5F]">Actualizar entregable</summary><form action={action} className="mt-2"><select name="status" defaultValue={deliverable.status} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">{Object.entries(deliverableLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><textarea name="result_summary" defaultValue={deliverable.result_summary ?? ''} minLength={3} maxLength={10000} rows={2} placeholder="Resultado (obligatorio al entregar o aceptar)..." className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" /><input name="evidence_reference" defaultValue={deliverable.evidence_reference ?? ''} minLength={3} maxLength={2000} placeholder="Enlace o referencia de evidencia..." className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" /><Feedback state={state} /><button disabled={pending} className="mt-2 rounded-lg border border-[#2F5D8C] px-3 py-2 text-sm font-semibold text-[#1E3A5F] disabled:opacity-50">{pending ? 'Actualizando...' : 'Guardar entregable'}</button></form></details></li>
}

function ProjectParticipantForm({ projectId, existingActorKeys }: { projectId: string; existingActorKeys: string[] }) {
  const [participantState, participantAction, participantPending] = useActionState(addProjectParticipantAction.bind(null, projectId), initialState)
  const [hasParticipantSelection, setHasParticipantSelection] = useState(false)

  return <form action={participantAction} className="mt-4 border-t border-slate-200 pt-4"><ProjectParticipantPicker disabled={participantPending} existingActorKeys={existingActorKeys} onSelectionChange={setHasParticipantSelection} /><input name="participation_role" required minLength={3} maxLength={200} placeholder="Rol en el proyecto..." className="mt-3 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /><textarea name="contribution_summary" required minLength={3} maxLength={10000} rows={2} placeholder="Contribución acordada..." className="mt-3 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /><Feedback state={participantState} /><button disabled={participantPending || !hasParticipantSelection} className="mt-3 rounded-xl border border-[#2F5D8C] px-4 py-2.5 text-sm font-semibold text-[#1E3A5F] disabled:opacity-50">{participantPending ? 'Incorporando...' : 'Incorporar participante'}</button></form>
}

export function ProjectOperationForms({ projectId, participants, deliverables, assigneeOptions }: { projectId: string; participants: ProjectParticipant[]; deliverables: ProjectDeliverable[]; assigneeOptions: OpportunityAssigneeOption[] }) {
  const [deliverableState, deliverableAction, deliverablePending] = useActionState(createProjectDeliverableAction.bind(null, projectId), initialState)

  return <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-950">Equipo del proyecto</h2><p className="mt-2 text-sm text-slate-600">La incorporación es explícita: elegí una persona u organización canónica. No crea vínculos con articulaciones u oportunidades.</p>{participants.length ? <ul className="mt-4 space-y-3">{participants.map((participant) => <ParticipantItem key={participant.participant_id} projectId={projectId} participant={participant} />)}</ul> : <p className="mt-4 text-sm text-slate-500">Todavía no hay participantes confirmados para la ejecución.</p>}<ProjectParticipantForm key={participants.map((participant) => participant.participant_id).join(',')} projectId={projectId} existingActorKeys={participants.map((participant) => `${participant.participant_type}:${participant.actor_id}`)} /></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-950">Entregables y evidencia</h2><p className="mt-2 text-sm text-slate-600">Una entrega realizada o aceptada debe tener un resultado y una referencia verificable de evidencia.</p>{deliverables.length ? <ul className="mt-4 space-y-3">{deliverables.map((deliverable) => <DeliverableItem key={deliverable.deliverable_id} projectId={projectId} deliverable={deliverable} />)}</ul> : <p className="mt-4 text-sm text-slate-500">Todavía no hay entregables planificados.</p>}<form action={deliverableAction} className="mt-4 border-t border-slate-200 pt-4"><input name="title" required minLength={3} maxLength={200} placeholder="Entregable" className="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /><textarea name="description" required minLength={3} maxLength={10000} rows={2} placeholder="Qué se espera entregar..." className="mt-3 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /><div className="mt-3 grid gap-3 sm:grid-cols-2"><select name="responsible_internal_user_id" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><option value="">Sin responsable inicial</option>{assigneeOptions.map((option) => <option key={option.id} value={option.id}>{option.display_name}</option>)}</select><input type="date" name="target_date" className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm" /></div><Feedback state={deliverableState} /><button disabled={deliverablePending} className="mt-3 rounded-xl border border-[#2F5D8C] px-4 py-2.5 text-sm font-semibold text-[#1E3A5F] disabled:opacity-50">{deliverablePending ? 'Registrando...' : 'Planificar entregable'}</button></form></section></div>
}
